# Generated by Django 6.0.1 on 2026-01-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadhistory',
            name='summary',
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='avg_flowrate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='avg_pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='avg_temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='total_equipment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
